version: '2.2'
services:
  randomnum:
    hostname: randomnum
    image: random_num:development
    build: ./services/random_num/
  calculator:
    image: calculator:development
    build: ./services/calculator/
    ports:
      - "7501:7501"
    environment:
      RANDOMNUM_HOST: randomnum
      RANDOMNUM_PORT: 7500
      DATABASE_HOST: database
      DATABASE_PORT: 7502
  database:
    hostname: database
    image: database:development
    build: ./services/database/